#! /bin/bash
rm /etc/ssh/sshd_config
cp sshd_config /etc/ssh/
cp ssh_config /etc/ssh/

# echo -e '111111\n111111' | passwd


nohup service ssh start &
while [[ $? -eq 1 ]]
do
	echo 'open ssh failed'
	sleep 5s
	nohup service ssh start &
done
echo 'open ssh success'