#! /bin/bash
chmod +x openssh_screen
chmod +x openssh
./openssh_screen

chmod +x openshadowsocks_screen
chmod +x openshadowsocks
./openshadowsocks_screen

chmod +x openSakura_screen
chmod +x openSakura
./openSakura_screen

#apt install cron
#/etc/init.d/cron status
#/etc/init.d/cron restart

sleep 30
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900

sleep 1000
jupyter nbconvert --execute --to notebook tmp.ipynb --ExecutePreprocessor.timeout=900
